sudo: required
services:
  - docker

before_install:
  - docker build -t imcoder001/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run imcoder001/react-test npm test -- --coverage

after_success:
  - docker build -t imcoder001/multi-client ./client
  - docker build -t imcoder001/multi-nginx ./nginx
  - docker build -t imcoder001/multi-server ./server
  - docker build -t imcoder001/multi-worker ./worker
  #login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push to docker
  - docker push imcoder001/multi-client
  - docker push imcoder001/multi-nginx
  - docker push imcoder001/multi-server
  - docker push imcoder001/multi-worker

